CREATE DATABASE [SignThoseSprocs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SignThoseSprocs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SignThoseSprocs.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SignThoseSprocs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SignThoseSprocs_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SignThoseSprocs] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [SignThoseSprocs] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET ARITHABORT OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SignThoseSprocs] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SignThoseSprocs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SignThoseSprocs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SignThoseSprocs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SignThoseSprocs] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SignThoseSprocs] SET  READ_WRITE 
GO
ALTER DATABASE [SignThoseSprocs] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SignThoseSprocs] SET  MULTI_USER 
GO
ALTER DATABASE [SignThoseSprocs] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SignThoseSprocs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SignThoseSprocs] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SignThoseSprocs]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SignThoseSprocs]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SignThoseSprocs] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
